# Default values for e7-gql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/entrello/e7-webcli/e7-webcli
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: registry-entrello
nameOverride: "e7-webcli"
fullnameOverride: "e7-webcli"

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  insecure:
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "false"
      traefik.ingress.kubernetes.io/router.middlewares: "ingress-redirect-scheme@kubernetescrd"
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "ingress-traefik-redirect-to-non-www@kubernetescrd,ingress-redirect-scheme@kubernetescrd"
  tls:
    - hosts:
        - app-staging.entrello.net
        - app-staging.entrello.at
        - app-staging.entrello.io
        - staging.entrello.io
  hosts:
    - host: app-staging.entrello.net
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: e7-webcli
            servicePort: 80
    - host: app-staging.entrello.at
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: e7-webcli
            servicePort: 80
    - host: app-staging.entrello.io
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: e7-webcli
            servicePort: 80
    - host: staging.entrello.io
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: e7-webcli
            servicePort: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

deploymentAnnotations:
  - name: "sidecar.jaegertracing.io/inject"
    value: "true"
